RunEnv: develop

ServerName: gapiservice

BasePath: "./"

Log:
  Level: 4
  Output: "stdout"
  FilePath: "./log"

Http:
  Addr: ":9000"

Gorm:
  Debug: true # 是否开启调试模式
  DBType: "mysql" # 数据库类型(目前支持的数据库类型：mysql)
  MaxLifetime: 7200 # 设置连接可以重用的最长时间(单位：秒)
  MaxOpenConns: 150 # 设置数据库的最大打开连接数
  MaxIdleConns: 50 # 设置空闲连接池中的最大连接数
  EnableAutoMigrate: true # 是否启用自动映射数据库表结构

MySQL:
  Host: "192.168.12.143" # 连接地址
  Port: 3306 # 连接端口
  User: "root" # 用户名
  Password: "root123" # 密码
  DBName: "inzone" # 数据库
  Parameters: "charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true" # 连接参数